### ISSUE TITLE
windows pc

### ISSUE THREAD

**Issue by mitchellhu** [hazzelnuts/ntfy-for-delphi#42]
### Discussed in https://github.com/orgs/hazzelnuts/discussions/36

<div type='discussions-op-text'>
Test VCL subscriber project, found there is no place to disable windows 10 system not show little notification window on the bottom-right side.  So, how to disable it by code?  
<sup>Originally posted by **artdelphi** February 19, 2023</sup>
how to sent notify to windows desktop?</div>

**Comment by p-samuel** [comment]
Hi @mitchellhu, that's only a demo but I manage to to solve on this commit.

[`93cec1e`](https://github.com/hazzelnuts/ntfy-for-delphi/commit/93cec1e18d75ba48d4e761c8042e9a8223e69fd3) 🚧 Final modifications
