### ISSUE TITLE
Proxy settings not implemented

### ISSUE THREAD

**Issue by bcp-software** [hazzelnuts/ntfy-for-delphi#45]
The library is unusable when a proxy server is required. The code simply provides no method to transfer proxy settings. (E.g. Indy HTTP supports it, but there's no interface to access it from the Ntfy library code). Please add a method:

    function Proxy(const AServer, APassword, AUsername: string; const APort: Integer): IRequest;

(Code example taken from RESTRequest4D.Request.Contract)

**Comment by p-samuel** [comment]
@bcp-software, [`Commits`](https://github.com/hazzelnuts/ntfy-for-delphi/pull/46/commits) are here
